name: "@name@"
description: "@description@"
version: "@version@"

spring:
  profiles:
    active: ${PROFILE}
  activemq:
    broker-url: ${emailCorp_receber_urlBroker}
    user: ${emailCorp_receber_usrBroker}   
    password: ${emailCorp_receber_pwdBroker}     
  mail:
    host: ${emailCorp_receber_mailHost}
    username: $emailCorp_receber_mailUserName
    password: ${emailCorp_receber_mailPwd}
    port: 25
    properties:
      mail:
        debug: false
        smtp:
          auth: true
          ehlo: false
          starttls:
            enable: false
server:
  port: 8092
  servlet:
    contextPath: /distribuirMail 

auth:
  codigoAplicacao: AUTORIZADOR-SERVICE      
  baseUrl: ${emailCorp_receber_authUrl}
  token-autenticacao: ${emailCorp_receber_authToken}
  
app:
  dirAnexos: ${emailCorp_receber_dirAnexos} 
