name: "@name@"
description: "@description@"
version: "@version@"

spring:
  profiles:
    active: ${PROFILE}
  activemq:
    broker-url: ${urlBroker}
    user: ${usrBroker}   
    password: ${pwdBroker} 
  mail:
    host: ${mailHost}
    username: ${mailUserName}
    password: ${mailPwd}
    port: ${mailPort}
    properties:
      mail:
        debug: false
        smtp:
          auth: true
          ehlo: false
          starttls:
            enable: false

server:
  port: 8092
  servlet:
    contextPath: /distribuirMail        

logging:
  config: ${arqConf}      
  
app:
  dirAnexos: ${dirAnexos}