spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      "[hibernate.format_sql]": true
      "[hibernate.ddl-auto]": update
  h2:
    console:
      enabled: true

springdoc:
  show-actuator: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
      
logging.config: classpath:log4j2-spring-hml.xml
